Add-Type -AssemblyName System.Drawing
$ErrorActionPreference = 'Stop'
# char codes: zheng lao shi jiao shi jie / kuai le o Q A Q
$codes = @(0x90D1,0x8001,0x5E08,0x6559,0x5E08,0x8282,0x5FEB,0x4E50,0x54E6,0x51,0x41,0x51)
$fontName = 'SimHei'
$GW = 18   # glyph width (cells)
$GH = 11   # glyph height (cells)
$out = New-Object System.Collections.Generic.List[string]
$out.Add('/* 18x11 dot font, auto-generated by genfont.ps1 */')
$out.Add('const char *GLYPH[12][11] = {')
$fmt = [System.Drawing.StringFormat]::GenericTypographic
$font = New-Object System.Drawing.Font($fontName, 18, [System.Drawing.FontStyle]::Bold, [System.Drawing.GraphicsUnit]::Pixel)
for ($i = 0; $i -lt 12; $i++) {
    $ch = [string][char]$codes[$i]
    # render at 2x height, then merge each 2 rows into 1 (compensate console cell aspect)
    $bmp = New-Object System.Drawing.Bitmap($GW, (2 * $GH))
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.Clear([System.Drawing.Color]::White)
    $g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::SingleBitPerPixelGridFit
    $sz = $g.MeasureString($ch, $font, 0, $fmt)
    $ox = [Math]::Max(0, ($GW - $sz.Width) / 2)
    $oy = [Math]::Max(0, (2 * $GH - $sz.Height) / 2)
    $g.DrawString($ch, $font, [System.Drawing.Brushes]::Black, $ox, $oy, $fmt)
    $g.Dispose()
    $out.Add(("    /* char {0} */ {{" -f $i))
    for ($y = 0; $y -lt $GH; $y++) {
        $row = '        "'
        for ($x = 0; $x -lt $GW; $x++) {
            $p1 = $bmp.GetPixel($x, 2 * $y)
            $p2 = $bmp.GetPixel($x, 2 * $y + 1)
            if (($p1.R + $p2.R) -lt 256) { $row += '#' } else { $row += '.' }
        }
        $row += '"'
        if ($y -lt ($GH - 1)) { $row += ',' }
        $out.Add($row)
    }
    $out.Add('    },')
    $bmp.Dispose()
}
$out.Add('};')
$out | Out-File -Encoding utf8 'h:\CYUYAN\font_js.h'
Write-Output 'OK'
