Add-Type -AssemblyName System.Drawing
$ErrorActionPreference = 'Stop'
# char codes: ni (U+4F60), hao (U+597D)  -> 16x16 dot font for OLED
$codes = @(0x4F60, 0x597D)
$names = @('NI', 'HAO')
$out = New-Object System.Collections.Generic.List[string]
$out.Add('/* 16x16 Chinese dot font, auto-generated by genfont16.ps1 (SimHei) */')
$out.Add('/* 1 bit per pixel, MSB = leftmost pixel; 2 bytes per row, 32 bytes per char */')
$fmt = [System.Drawing.StringFormat]::GenericTypographic
$font = New-Object System.Drawing.Font('SimHei', 16, [System.Drawing.FontStyle]::Regular, [System.Drawing.GraphicsUnit]::Pixel)
for ($i = 0; $i -lt 2; $i++) {
    $ch = [string][char]$codes[$i]
    $bmp = New-Object System.Drawing.Bitmap(16, 16)
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.Clear([System.Drawing.Color]::White)
    $g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::SingleBitPerPixelGridFit
    $sz = $g.MeasureString($ch, $font, 0, $fmt)
    $ox = [Math]::Max(0, (16 - $sz.Width) / 2)
    $oy = [Math]::Max(0, (16 - $sz.Height) / 2)
    $g.DrawString($ch, $font, [System.Drawing.Brushes]::Black, $ox, $oy, $fmt)
    $g.Dispose()
    $out.Add(("/* {0} (U+{1:X4}) */" -f $ch, $codes[$i]))
    $out.Add(("const unsigned char FONT16_{0}[32] = {{" -f $names[$i]))
    for ($y = 0; $y -lt 16; $y++) {
        $b1 = 0; $b2 = 0
        for ($x = 0; $x -lt 8; $x++) {
            if ($bmp.GetPixel($x, $y).R -lt 128)     { $b1 = $b1 -bor (1 -shl (7 - $x)) }
            if ($bmp.GetPixel($x + 8, $y).R -lt 128) { $b2 = $b2 -bor (1 -shl (7 - $x)) }
        }
        $out.Add(("    0x{0:X2}, 0x{1:X2}," -f $b1, $b2))
    }
    $out.Add('};')
    $out.Add('')
    # ASCII preview to console
    "preview of $ch :"
    for ($y = 0; $y -lt 16; $y++) {
        $row = ''
        for ($x = 0; $x -lt 16; $x++) {
            if ($bmp.GetPixel($x, $y).R -lt 128) { $row += '#' } else { $row += '.' }
        }
        $row
    }
    $bmp.Dispose()
}
$out | Out-File -Encoding ascii 'h:\CYUYAN\STM32L0_OLED\font16.h'
Write-Output 'font16.h OK'
